export * from './HomePage/HomePage'
export * from './LoginPage/LoginPage'
export * from './ResultsPage/ResultsPage'
export * from './MapPage/MapPage'
export * from './ProfilePage/ProfilePage'
export * from './VideoPage/VideoPage'
export * from './introduccion/intro'